runtime: python39  

entrypoint: gunicorn -b :$PORT youtube_dashboard:app

env: standard
instance_class: F1  # Specifies an instance class, adjust as needed.

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_idle_instances: automatic  # Adjusts automatically. Change to a number if you need a specific count.
  max_idle_instances: automatic  # Adjusts automatically. Change to a number if you need a specific count.
  min_pending_latency: automatic  # Adjusts automatically. Specify times like '100ms' for specific needs.
  max_pending_latency: automatic
